### ISSUE TITLE
Ability to use another database config as default config

### ISSUE THREAD

**Issue by debuqer** [escherchia/laraval-scenario-logger#8]
Some of developers are tend to isolate logs database rather than application database.
it might be a good practice to set our database config name in config/laravel-scenario-logger.php

```php
'drivers' => [
        'database' => [
            'default-database-connection' => 'my_logs_storage_config',
        ]
    ],

``` 

and in config/database.php we will have a connection named 'my_logs_storage_config'.

Thank in advance

**Comment by mehrdadmahdian** [comment]
Thanks for your elegant recommendation. 
The feature was one of our wishlists which was not listed in the project readme. 

Keep track of this issue, we will develop it ASAP.
